format = """
[$directory](bold cyan)($git_branch$git_state$git_status)($aws)($kubernetes)
[»](bold green) """

[git_branch]
style = "bold green"
format = "[\\[[$branch$tag](bold green)\\]](bold white)"

[git_status]
format = ' ([\[$conflicted$deleted$renamed$modified$staged$untracked$ahead_behind\]]($style))'

[directory]
style = "bold cyan"
truncate_to_repo = false
truncation_length = 1
fish_style_pwd_dir_length = 1

[python]
scan_for_pyfiles = false

[ruby]
disabled = true

[swift]
disabled = true

[hostname]
ssh_only = false
format = "[$hostname]($style)"
style = "bold white"

[username]
show_always = true
style_user = "bold white"
format = "[$user]($style)"

[time]
disabled = false
format = "[$time]($style)"
time_format = "%H:%M"

[aws]
format = ' on [$symbol($profile )(\($region\) )]($style)'
style = "bold yellow"
symbol = " "
[aws.region_aliases]
ap-southeast-2 = "au"
us-east-1 = "va"
[aws.profile_aliases]
CompanyGroupFrobozzOnCallAccess = 'Frobozz'

[kubernetes]
format = 'on [ ($context)]($style) '
style = "bold cyan"
disabled = false
[kubernetes.context_aliases]
"arn:aws:eks:eu-central-1:532985982628:cluster/nkb-dev-eks-cluster" = "nkb_dev"
